apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args:
        - run
        - /etc/alloy/config.alloy
        volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy

      volumes:
      - name: alloy-config
        configMap:
          name: alloy-config